### ISSUE TITLE
CC License with NoDerivatives?

### ISSUE THREAD

**Issue by karfau** [bobvann/GPIOSim#3]
If I understand the CC license correctly that you have put into the LICENSE file,
it is not allowed to change the code (without asking you for permission)?

Is that really what you wanted to achieve?
(Wouldn't that mean that while I can fork the repository, 
I would need to ask you before I can make changes to the code?)

Best karfau

**Comment by bobvann** [comment]
Yes, correct.

What changes would you like to do?

**Comment by bobvann** [comment]
Changed license to GNU GPL

**Comment by karfau** [comment]
:+1: thx for opening up the license this way
